name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dev" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  LATEST_TAG: schoolboy215/boggle-server:dev

  # Variables for making the placeholder .env file
  SESSION_SECRET: \"secret12345\""
  CERT_PATH: "\"\""
  KEY_PATH: "\"\""
  PORT: 80
  SKIP_TLS: 1
  GAME_LENGTH: 180
  ROOMCODE_BYTES: 2
  MAX_MULTIBOARD_GEN: 10

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create and populate .env file
      run: |
        touch .env
        echo SESSION_SECRET="$SESSION_SECRET" >> .env
        echo CERT_PATH="$CERT_PATH" >> .env
        echo KEY_PATH="$KEY_PATH" >> .env
        echo PORT="$PORT" >> .env
        echo SKIP_TLS="$SKIP_TLS" >> .env
        echo GAME_LENGTH="$GAME_LENGTH" >> .env
        echo ROOMCODE_BYTES="$ROOMCODE_BYTES" >> .env
        echo MAX_MULTIBOARD_GEN="$MAX_MULTIBOARD_GEN" >> .env

        echo "cat .env"
        cat .env

        echo "ls -a ."
        ls -a .

        echo "ls -a ${{ github.workspace }}"
        ls -a ${{ github.workspace }}
      shell: bash
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build .
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Create and populate .env file
        run: |
          touch .env
          echo SESSION_SECRET="$SESSION_SECRET" >> .env
          echo CERT_PATH="$CERT_PATH" >> .env
          echo KEY_PATH="$KEY_PATH" >> .env
          echo PORT="$PORT" >> .env
          echo SKIP_TLS="$SKIP_TLS" >> .env
          echo GAME_LENGTH="$GAME_LENGTH" >> .env
          echo ROOMCODE_BYTES="$ROOMCODE_BYTES" >> .env
          echo MAX_MULTIBOARD_GEN="$MAX_MULTIBOARD_GEN" >> .env

          echo "cat .env"
          cat .env

          echo "ls -a ."
          ls -a .

          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.LATEST_TAG }}
